version: 2

jobs:
 build:
   machine: true
   working_directory: ~/workspace

   steps:
     - checkout

     - run:
         name: Build docker image
         command: |
           docker build -t ubuntu-git:20.04 .

     - run:
         name: Push to docker hub
         command: |
           docker login -u $DOCKER_LOGIN_ID -p $DOCKER_LOGIN_PASSWORD
           docker push ${CIRCLE_USERNAME}/ubuntu-git:20.04

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
